---
- name: install
  hosts: all 
  remote_user: ansible
  
  tasks:
  - name: ansible_os_family 
    debug: 
      msg: '{{ansible_os_family}}'
  - name: httpd package update
    yum:
      name: httpd
      state: latest 
    become: true
    when: ansible_os_family == 'RedHat'

  - name: apache2  package update
    apt:
      name: apache
      state: latest 
    become: true
    when: ansible_os_family == 'Debian'


