---
- name: install
  hosts: db1 
  remote_user: ansible 
  
  tasks:
  - name: count process   
    shell: ps | wc -l
    register: remote_processes_number
  - name: print remote running process   
    debug: 
      msg: '{{remote_processes_number.stdout}}'
  - name: count process local system  
    shell: ps | wc -l
    delegate_to: localhost
    register: local_processes_number
  - name: print local running process   
    debug: 
      msg: '{{local_processes_number.stdout}}'
