---
- name: install
  hosts: web 
  remote_user: ansible
  
  tasks:
  - name: website present update 
    template: 
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    become: true
