---
- name: install
  hosts: all 
  remote_user: ansible
  
  tasks:
  - name: ansible_os_family 
    debug: 
      msg: '{{ansible_os_family}}'
  - name: httpd package update
    import_tasks: redhat.yml 
    when: ansible_os_family == 'RedHat'
    become: true


