---

- name: vars file  
  hosts: localhost
  gather_facts: false
  remote_user: root
  tasks:
  - name: load variables  
    include_vars: "{{varfile}}"
  - name: a task  
    debug:
      msg: "i am a {{name}}" 
  
