---
- name: install
  hosts: localhost
  gather_facts: false
  remote_user: root 
  tasks:
  - name: query session  
    command: /sbin/iscsiadm -m session
    register: sessions
    failed_when: sessions.rc not in (0,21) 

