---
- name: install
  hosts: localhost
  gather_facts: false
  remote_user: root 
  vars:
    num1: 10
    num3: 10
  tasks:
  - name: logic and comparison  
    debug:
      msg: "can you read mn?"
    when: num1 >= num3 and num1 is even and num2 is not defined  


