---

- name: vars file  
  hosts: localhost
  gather_facts: true
  remote_user: root
  tasks:
  - name: load variables  
    include_vars: "{{item}}"
    with_first_found:
      - "{{ansible_distribution}}.yaml"
      - "{{ansible_os_family}}.yaml"
      - variables.yml

  - name: a task  
    debug:
      msg: "i am a {{name}}" 
  
