---
- name: install
  hosts: localhost
  gather_facts: false
  remote_user: root 
  tasks:
  - include: files.yml 
    vars: 
      path: /tmp/foo
      file: herp  

  - include: files.yml 
    vars: 
      path: /tmp/foo
      file: derp  
