---

- name: localhost  
  hosts: localhost 
  gather_facts: false
  remote_user: root
  tasks:
  - name: do a thing
    uri:
      url: https://derpops.bike
    register: derpops
 
  - name: show derpops  
    debug: 
      var: derpops.server

  - name: display derpops 
    debug: 
      msg: "{{derpops}}"
