---
- name: install
  hosts: all 
  remote_user: root
  
  tasks:
  - name: motd file ensure   
    template: 
      src: motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
    become: true 
