---
- name: install
  hosts: web 
  remote_user: ansible
  
  tasks:
  - name: httpd install
    yum: 
      name: httpd
      state: present 
    become: true 
  - name: http start enable
    service:
      name: httpd
      state: started
      enabled: true
    become: true
  - name: http config update 
    copy:
      src: website.conf
      dest: /etc/httpd.conf.d
    become: true
    notify: Restart HTTPd
  handlers:
  - name: Restart HTTPd
    service:
      name: httpd
      state: restarted
    become: true 
