---
- name: install
  hosts: web 
  remote_user: ansible
  
  tasks:
  - name: create folder /tmp/dirXY from 1 to 10  
    file: 
      dest: '/tmp/dir{{item}}'
      state: directory
    with_sequence: start=1 end=10 
    become: true
   
