---
- name: install
  hosts: webserver 
  remote_user: ansible
  
  tasks:
  - name: checking httpd service
    service: 
      name: httpd
      state: started
    register: httpd_result 
    ignore_errors: true
  - name: debug msg
    debug: 
      msg: previous task failed
    when: httpd_result|failed
